app {
  name = "Receiptly OCR"
  pollIntervalSeconds = 120
}

database {
  url = "postgresql://localhost:5432/receiptly"
  user = ${?POSTGRES_USER}
  user = "postgres"
  password = ${?POSTGRES_PASSWORD}
  password = "postgres"
  maxPoolSize = 5
}

telegram {
  botToken = ${?TELEGRAM_BOT_TOKEN}
  botToken = ""
}
