app {
  name = "Receiptly"
  port = 8083
  host = "0.0.0.0"
}

database {
  url = "jdbc:postgresql://localhost:5432/receiptly"
  driver = "org.postgresql.Driver"
  user = ${?POSTGRES_USER}
  user = "postgres"
  password = ${?POSTGRES_PASSWORD}
  password = "postgres"
  maxPoolSize = 10
}

telegram {
  botToken = ${?TELEGRAM_BOT_TOKEN}
  webhookPath = "/telegram/webhook"
}
